### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MathMendesReis** [BrunaSpaniol/toDoList#3]
1 - Desing ficou top, identico ao do figma, arrasou!
2 - Seu codigo e extremamente organizado, você cosegue separar bem os blocos de codigo css, fica facil de ler.
3 - Vocẽ e boa no raciocio logico, com poucas linhas consegue seu objetivo

**Comment by MathMendesReis** [comment]
https://github.com/BrunaSpaniol/toDoList/blob/ed94da3672089b1929015f5f0824d097d61a3057/src/components/CreateTaskBar.tsx#L32C1-L33C1

Aqui nesse trecho de codigo, da pra usar um form ao inves de div, fica mais semantico, além de melhorar a acessibilidade, por exemplo, adicionando um form, adicionando um e.prevent.defaul() ma função que add a task e type submit no button, o usuario vai adicionar a task sem mecher no mouse, e so escrever e apertar enter que ja vai funcionar.

https://github.com/BrunaSpaniol/toDoList/blob/ed94da3672089b1929015f5f0824d097d61a3057/src/components/CreateTaskBar.tsx#L32

Aqui da pra melhorarar a semantica e acessibilidade, voce pode usar uma tag form aqui e button submit, que vai garantir que o usuario consiga adicionar uma tarefa com o teclado.

**Comment by MathMendesReis** [comment]
https://github.com/BrunaSpaniol/toDoList/blob/ed94da3672089b1929015f5f0824d097d61a3057/src/components/CreateTaskBar.tsx#L32

Aqui da pra melhorarar a semantica e acessibilidade, voce pode usar uma tag form aqui e button submit, que vai garantir que o usuario consiga adicionar uma tarefa com o teclado.

**Comment by MathMendesReis** [comment]
https://github.com/BrunaSpaniol/toDoList/blob/ed94da3672089b1929015f5f0824d097d61a3057/src/components/CreateTaskBar.tsx#L13

Aqui tu pode colocar algo que impeça de inserir uma task vazia.

**Comment by MathMendesReis** [comment]
https://github.com/BrunaSpaniol/toDoList/blob/ed94da3672089b1929015f5f0824d097d61a3057/src/components/Task.tsx#L28

faltou so um gap pra afastar as tarefas,

Parabens, seu projeto ficou da horaa! S2

**Comment by BrunaSpaniol** [comment]
> https://github.com/BrunaSpaniol/toDoList/blob/ed94da3672089b1929015f5f0824d097d61a3057/src/components/CreateTaskBar.tsx#L13
> 
> Aqui tu pode colocar algo que impeça de inserir uma task vazia.

Coloquei para desabilitar o botão caso o estado for vazio
